theme: jekyll-theme-minimal
show_downloads: true
google_analytics:
title: Subodh Pushkar
description: >
  <br><br>
  <a herf="https://www.linkedin.com/in/subodh-pushkar-595956b9/">LinkedIn</a>
logo: "/images/avatar.png?raw=true"