title: Subodh Pushkar
email: subodh.pushkar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

  Subodh Pushkar protal website to access all links and resources
  related to me 😎
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
